iapiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: app-python
        image: juanchovelezpro/apppython
        livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 5
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred